local FS = require("core.fs")
local Logger = require("core.logger")

local M = {}

function M.generate(env_table, output_path)
    output_path = output_path or FS.expand_path("~/.config/lem/env.sh")
    FS.ensure_dir(FS.expand_path("~/.config/lem"))
    local lines = { "#!/bin/bash", "# Generated by LEM - do not edit manually", "" }
    local keys = {}
    for k in pairs(env_table) do keys[#keys + 1] = k end
    table.sort(keys)
    for _, k in ipairs(keys) do
        lines[#lines + 1] = string.format('export %s="%s"', k, env_table[k])
    end
    local content = table.concat(lines, "\n") .. "\n"
    local ok, err = FS.write(output_path, content)
    if ok then Logger.info("Environment file generated: " .. output_path) end
    return ok, err
end

function M.show()
    local path = FS.expand_path("~/.config/lem/env.sh")
    if FS.file_exists(path) then return FS.read(path) end
    return nil, "no environment file found"
end

function M.merge(env_list)
    local merged = {}
    for _, env_table in ipairs(env_list) do
        for k, v in pairs(env_table) do merged[k] = v end
    end
    return merged
end

return M
