-- src/core/init.lua
-- Environment auto-initialization module

local FS = require("core.fs")
local Logger = require("core.logger")
local DB = require("core.db")

local M = {}

------------------------------------------------------------------------
-- Internal helpers
------------------------------------------------------------------------

--- Run a shell command bypassing the executor whitelist.
-- Used for build-tool checks (gcc, pkg-config, make) that are not whitelisted.
-- @param cmd string
-- @return boolean  true if exit code is 0
local function shell_ok(cmd)
    local ok = os.execute(cmd .. " >/dev/null 2>&1")
    return ok == true or ok == 0
end

--- Get file size in bytes.
-- @param path string
-- @return number|nil  size in bytes, or nil on error
local function file_size(path)
    local f = io.open(path, "r")
    if not f then return nil end
    local size = f:seek("end")
    f:close()
    return size
end

--- Format bytes into human-readable string.
-- @param bytes number
-- @return string
local function format_size(bytes)
    if not bytes then return "unknown" end
    if bytes < 1024 then return bytes .. " B" end
    if bytes < 1024 * 1024 then return string.format("%.1f KB", bytes / 1024) end
    return string.format("%.1f MB", bytes / (1024 * 1024))
end

------------------------------------------------------------------------
-- Check whether the environment has already been initialised
------------------------------------------------------------------------

function M.is_initialized()
    local marker = FS.expand_path("~/.local/share/lem/.initialized")
    return FS.file_exists(marker)
end

------------------------------------------------------------------------
-- Full initialisation
------------------------------------------------------------------------

function M.initialize(force, opts)
    opts = opts or {}
    local dry = opts.dry_run

    if M.is_initialized() and not force then
        print("LEM is already initialized.")
        print("Use 'lem init --force' to reinitialize.")
        return true
    end

    if dry then
        print("LEM init --dry-run: showing what would be done")
        print("")
    else
        print("Initializing LEM environment...")
        print("")
    end

    -- Step 1: Create directory structure ----------------------------
    print("[1/6] Creating directories...")
    local dirs = {
        FS.expand_path("~/.config/lem"),
        FS.expand_path("~/.config/lem/sources"),
        FS.expand_path("~/.config/lem/recipes"),
        FS.expand_path("~/.local/share/lem"),
        FS.expand_path("~/.local/share/lem/backups"),
        FS.expand_path("~/.cache/lem"),
    }
    for _, dir in ipairs(dirs) do
        if dry then
            print("  [dry-run] mkdir -p " .. dir)
        else
            FS.ensure_dir(dir)
            Logger.debug("Created directory: " .. dir)
        end
    end
    print("  Done.")

    -- Step 2: Generate default user config --------------------------
    print("[2/6] Generating default configuration...")
    local user_config = FS.expand_path("~/.config/lem/config.lua")
    if not FS.file_exists(user_config) then
        local config_content = [[-- LEM User Configuration
-- This file is auto-generated. Edit as needed.
return {
    -- Default package manager ("apt" or "docker")
    default_manager = "apt",

    -- Log level: "DEBUG", "INFO", "WARN", "ERROR"
    log_level = "INFO",

    -- Auto-confirm installations
    auto_confirm = false,

    -- Command timeout in seconds
    timeout = 300,
}
]]
        if dry then
            print("  [dry-run] write ~/.config/lem/config.lua")
        else
            FS.write(user_config, config_content)
        end
        print("  Created: ~/.config/lem/config.lua")
    else
        print("  Skipped: config already exists")
    end

    -- Step 3: Initialise SQLite database ----------------------------
    if not opts.skip_db then
        print("[3/6] Initializing state database...")
        local data_dir = FS.expand_path("~/.local/share/lem")
        if dry then
            print("  [dry-run] DB.init(" .. data_dir .. ")")
        else
            DB.init(data_dir)
            -- Note: DB is intentionally left open; caller (cli.lua) manages lifecycle
        end
        print("  Created: ~/.local/share/lem/state.db")
    else
        print("[3/6] Skipping database initialization (--skip-db).")
    end

    -- Step 4: Generate environment file -----------------------------
    print("[4/6] Generating environment file...")
    local env_sh = FS.expand_path("~/.config/lem/env.sh")
    if not FS.file_exists(env_sh) then
        local env_content = [[#!/bin/bash
# LEM Environment Variables
# Generated by lem init
# Add your custom variables below:

]]
        if dry then
            print("  [dry-run] write ~/.config/lem/env.sh")
        else
            FS.write(env_sh, env_content)
        end
        print("  Created: ~/.config/lem/env.sh")
    else
        print("  Skipped: env.sh already exists")
    end

    -- Step 5: Configure shell integration ---------------------------
    if not opts.skip_shell then
        print("[5/6] Setting up shell integration...")
        local home = FS.expand_path("~")
        local shell_rc = nil

        -- Detect user shell
        local shell = os.getenv("SHELL") or "/bin/bash"
        if shell:match("zsh") then
            shell_rc = home .. "/.zshrc"
        elseif shell:match("bash") then
            if FS.file_exists(home .. "/.bashrc") then
                shell_rc = home .. "/.bashrc"
            else
                shell_rc = home .. "/.bash_profile"
            end
        end

        if shell_rc then
            local source_line = '# LEM environment\n[ -f ~/.config/lem/env.sh ] && source ~/.config/lem/env.sh'
            local needs_update = true

            if FS.file_exists(shell_rc) then
                local content = FS.read(shell_rc)
                if content and content:match("lem/env%.sh") then
                    needs_update = false
                    print("  Skipped: shell integration already configured")
                end
            end

            if needs_update then
                if dry then
                    print("  [dry-run] append source line to " .. shell_rc)
                else
                    local existing = FS.read(shell_rc) or ""
                    FS.write(shell_rc, existing .. "\n" .. source_line .. "\n")
                end
                print("  Added source line to " .. shell_rc)
            end
        else
            print("  Skipped: could not detect shell")
        end
    else
        print("[5/6] Skipping shell integration (--skip-shell).")
    end

    -- Step 6: Try to compile C native modules -----------------------
    if not opts.skip_compile then
        print("[6/6] Checking C native modules...")
        local lem_root = _G.LEM_ROOT
        if lem_root then
            local makefile = lem_root .. "/native/Makefile"
            if FS.file_exists(makefile) then
                -- Check for gcc (not in executor whitelist, use shell directly)
                if shell_ok("which gcc") then
                    -- Check for lua5.4 dev headers
                    local lua_ok = shell_ok("pkg-config --exists lua5.4") or
                                   shell_ok("pkg-config --exists lua")
                    if lua_ok then
                        if dry then
                            print("  [dry-run] make -C " .. lem_root .. "/native")
                        else
                            print("  Compiling native modules...")
                            local make_ok = shell_ok("make -C " .. lem_root .. "/native")
                            if make_ok then
                                print("  Native modules compiled successfully.")
                            else
                                print("  Warning: compilation failed, using Lua fallback.")
                            end
                        end
                    else
                        print("  Skipped: lua5.4 dev headers not found (install liblua5.4-dev)")
                    end
                else
                    print("  Skipped: gcc not found")
                end
            end
        else
            print("  Skipped: LEM_ROOT not set")
        end
    else
        print("[6/6] Skipping C native module compilation (--skip-compile).")
    end

    -- Write initialisation marker -----------------------------------
    local marker = FS.expand_path("~/.local/share/lem/.initialized")
    if dry then
        print("[dry-run] write " .. marker)
        print("")
        print("No changes were made (dry-run mode).")
    else
        FS.write(marker, os.date("%Y-%m-%d %H:%M:%S"))
        print("")
        print("LEM environment initialized successfully!")
    end
    print("")
    print("Next steps:")
    print("  source ~/.config/lem/env.sh   # Load environment variables")
    print("  lem help                      # See available commands")
    print("  lem apply dev                 # Set up dev environment")

    return true
end

------------------------------------------------------------------------
-- Check initialisation status (machine-readable)
------------------------------------------------------------------------

function M.check()
    local status = {}
    local missing = {}
    local missing_count = 0

    -- Check marker
    local marker = FS.expand_path("~/.local/share/lem/.initialized")
    status.initialized = FS.file_exists(marker)

    -- Check directories
    local dirs = {
        config   = FS.expand_path("~/.config/lem"),
        data     = FS.expand_path("~/.local/share/lem"),
        cache    = FS.expand_path("~/.cache/lem"),
        backups  = FS.expand_path("~/.local/share/lem/backups"),
    }
    status.dirs = {}
    for name, path in pairs(dirs) do
        local exists = FS.file_exists(path)
        status.dirs[name] = exists
        if not exists then
            missing[#missing + 1] = { type = "dir", name = name, path = path }
            missing_count = missing_count + 1
        end
    end

    -- Check config file
    status.config = FS.file_exists(FS.expand_path("~/.config/lem/config.lua"))
    if not status.config then
        missing[#missing + 1] = { type = "file", name = "config", path = FS.expand_path("~/.config/lem/config.lua") }
        missing_count = missing_count + 1
    end

    -- Check env.sh
    status.env_sh = FS.file_exists(FS.expand_path("~/.config/lem/env.sh"))
    if not status.env_sh then
        missing[#missing + 1] = { type = "file", name = "env_sh", path = FS.expand_path("~/.config/lem/env.sh") }
        missing_count = missing_count + 1
    end

    -- Check DB
    status.db = FS.file_exists(FS.expand_path("~/.local/share/lem/state.db"))
    if not status.db then
        missing[#missing + 1] = { type = "file", name = "db", path = FS.expand_path("~/.local/share/lem/state.db") }
        missing_count = missing_count + 1
    end

    -- Check shell integration
    local home = FS.expand_path("~")
    local shell = os.getenv("SHELL") or "/bin/bash"
    local shell_rc
    if shell:match("zsh") then
        shell_rc = home .. "/.zshrc"
    elseif shell:match("bash") then
        shell_rc = home .. "/.bashrc"
    end
    status.shell_rc = shell_rc
    status.shell_type = shell
    status.shell_integrated = false
    if shell_rc and FS.file_exists(shell_rc) then
        local content = FS.read(shell_rc)
        if content and content:match("lem/env%.sh") then
            status.shell_integrated = true
        end
    end
    if not status.shell_integrated then
        missing[#missing + 1] = { type = "shell", name = "shell_integration", path = shell_rc }
        missing_count = missing_count + 1
    end

    -- Check native modules
    local lem_root = _G.LEM_ROOT
    status.native_modules = false
    if lem_root then
        status.native_modules = FS.file_exists(lem_root .. "/native/lem_db.so") or
                                FS.file_exists(lem_root .. "/native/lem_executor.so")
    end

    -- Determine init_state: "uninitialized" | "partial" | "complete"
    local all_ok = (missing_count == 0)
    if not status.initialized and missing_count > 0 then
        status.init_state = "uninitialized"
    elseif all_ok then
        status.init_state = "complete"
    else
        status.init_state = "partial"
    end

    status.missing = missing
    status.missing_count = missing_count
    status.all_ok = all_ok
    return status
end

------------------------------------------------------------------------
-- Human-readable environment report
------------------------------------------------------------------------

function M.report(verbose)
    local status = M.check()

    print("LEM Environment Report")
    print("======================")
    print("")

    -- Initialization state
    print("State: " .. status.init_state)
    if status.initialized then
        local marker = FS.expand_path("~/.local/share/lem/.initialized")
        local ts = FS.read(marker)
        if verbose then
            print("Initialized: yes")
            print("  Timestamp : " .. (ts or "unknown"))
            local sz = file_size(marker)
            print("  Marker    : " .. marker .. " (" .. format_size(sz) .. ")")
        else
            print("Initialized: yes" .. (ts and " (" .. ts .. ")" or ""))
        end
    else
        print("Initialized: no")
    end

    -- Directories
    print("")
    print("Directories:")
    for name, exists in pairs(status.dirs) do
        if verbose then
            local path_map = {
                config  = FS.expand_path("~/.config/lem"),
                data    = FS.expand_path("~/.local/share/lem"),
                cache   = FS.expand_path("~/.cache/lem"),
                backups = FS.expand_path("~/.local/share/lem/backups"),
            }
            local p = path_map[name] or "?"
            print("  " .. name .. ": " .. (exists and "ok" or "MISSING") .. "  (" .. p .. ")")
        else
            print("  " .. name .. ": " .. (exists and "ok" or "MISSING"))
        end
    end

    -- Config / Env / DB
    print("")
    if verbose then
        local config_path = FS.expand_path("~/.config/lem/config.lua")
        local env_path    = FS.expand_path("~/.config/lem/env.sh")
        local db_path     = FS.expand_path("~/.local/share/lem/state.db")
        print("Config:    " .. (status.config and "exists" or "MISSING") ..
              "  " .. config_path ..
              (status.config and " (" .. format_size(file_size(config_path)) .. ")" or ""))
        print("Env file:  " .. (status.env_sh and "exists" or "MISSING") ..
              "  " .. env_path ..
              (status.env_sh and " (" .. format_size(file_size(env_path)) .. ")" or ""))
        print("Database:  " .. (status.db and "exists" or "MISSING") ..
              "  " .. db_path ..
              (status.db and " (" .. format_size(file_size(db_path)) .. ")" or ""))
    else
        print("Config:    " .. (status.config and "~/.config/lem/config.lua (exists)" or "MISSING"))
        print("Env file:  " .. (status.env_sh and "~/.config/lem/env.sh (exists)" or "MISSING"))
        print("Database:  " .. (status.db and "~/.local/share/lem/state.db (exists)" or "MISSING"))
    end

    -- Shell
    print("")
    if verbose then
        print("Shell type:    " .. (status.shell_type or "unknown"))
        print("Shell rc:      " .. (status.shell_rc or "not detected"))
        print("Integrated:    " .. (status.shell_integrated and "yes" or "no"))
    else
        print("Shell:         " .. (status.shell_rc or "unknown"))
        print("Integrated:    " .. (status.shell_integrated and "yes" or "no"))
    end

    -- Native modules
    print("")
    if verbose then
        local lem_root = _G.LEM_ROOT
        print("Native modules: " .. (status.native_modules and "compiled" or "not compiled (using Lua fallback)"))
        if lem_root then
            local so_db  = lem_root .. "/native/lem_db.so"
            local so_exec = lem_root .. "/native/lem_executor.so"
            print("  lem_db.so      : " .. (FS.file_exists(so_db) and format_size(file_size(so_db)) or "not found"))
            print("  lem_executor.so: " .. (FS.file_exists(so_exec) and format_size(file_size(so_exec)) or "not found"))
        end
    else
        print("Native modules: " .. (status.native_modules and "compiled" or "not compiled (using Lua fallback)"))
    end

    -- Missing summary
    if status.missing_count > 0 then
        print("")
        print("Missing items (" .. status.missing_count .. "):")
        for _, item in ipairs(status.missing) do
            print("  - [" .. item.type .. "] " .. item.name ..
                  (item.path and "  (" .. item.path .. ")" or ""))
        end
        print("")
        print("Run 'lem init' to fix missing items.")
    end

    return status
end

------------------------------------------------------------------------
-- Cleanup (for uninstall scenarios)
------------------------------------------------------------------------

function M.cleanup()
    print("Warning: This will remove LEM data but keep installed packages.")
    print("LEM config and data directories will be preserved.")

    local marker = FS.expand_path("~/.local/share/lem/.initialized")
    if FS.file_exists(marker) then
        os.remove(marker)
        print("Initialization marker removed.")
    end
    return true
end

return M
